In [1]:
import gymnasium
import QGym

In [2]:
env = gymnasium.make('QGym/Qiskit-v0', size=3)

In [3]:
observation, info = env.reset()

/home/kknopp/Documents/Work/QWorld/env/lib/python3.11/site-packages/gymnasium/utils/passive_env_checker.py:197: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/kknopp/Documents/Work/QWorld/env/lib/python3.11/site-packages/gymnasium/utils/passive_env_checker.py:210: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/kknopp/Documents/Work/QWorld/env/lib/python3.11/site-packages/gymnasium/utils/passive_env_checker.py:160: UserWarning: WARN: The obs returned by the `reset()` method was expecting a numpy array, actual type: <class 'list'>
  logger.warn(
/home/kknopp/Documents/Work/QWorld/env/lib/python3.11/site-packages/gymnasium/spaces/box.py:230: UserWarning: WARN: Casting i

In [4]:
observation

[1, 0, 0, 0, 0, 0, 0, 0]

In [5]:
for _ in range(100):
    action = env.action_space.sample()  # agent policy that uses the observation and info
    observation, reward, terminated, truncated, info = env.step(action)

    if terminated:
        break
    
    print(observation, reward)

env.close()

/home/kknopp/Documents/Work/QWorld/env/lib/python3.11/site-packages/gymnasium/utils/passive_env_checker.py:188: UserWarning: WARN: The obs returned by the `step()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")


[1. 0. 0. 0. 0. 0. 0. 0.] 0.0
[1. 0. 0. 0. 0. 0. 0. 0.] 0.0
[1. 0. 0. 0. 0. 0. 0. 0.] 0.0
[1. 0. 0. 0. 0. 0. 0. 0.] 0.0
[0.5 0.5 0.  0.  0.  0.  0.  0. ] 0.0
[0.5 0.5 0.  0.  0.  0.  0.  0. ] 0.0
[0.5 0.5 0.  0.  0.  0.  0.  0. ] 0.0
[0.5 0.5 0.  0.  0.  0.  0.  0. ] 0.0
[0.5 0.5 0.  0.  0.  0.  0.  0. ] 0.0
[0.  0.  0.  0.  0.5 0.5 0.  0. ] 0.0
[0.  0.  0.  0.  0.5 0.5 0.  0. ] 0.0
[0.  0.  0.  0.  0.5 0.5 0.  0. ] 0.0
[0.  0.  0.  0.  0.  0.  0.5 0.5] 0.4999999999999999
[0.  0.  0.  0.  0.  0.  0.5 0.5] 0.4999999999999998
[0.   0.   0.   0.   0.25 0.25 0.25 0.25] 0.24999999999999994
[0.   0.   0.   0.   0.25 0.25 0.25 0.25] 0.2499999999999999
[0.25 0.25 0.25 0.25 0.   0.   0.   0.  ] 0.0
[0.25 0.25 0.25 0.25 0.   0.   0.   0.  ] 0.0
[0.25 0.25 0.25 0.25 0.   0.   0.   0.  ] 0.0
[0.   0.   0.   0.   0.25 0.25 0.25 0.25] 0.2499999999999999
[0.   0.   0.   0.   0.25 0.25 0.25 0.25] 0.24999999999999983
[0.   0.   0.   0.   0.25 0.25 0.25 0.25] 0.24999999999999978
[0.00000000e+00 0.000000